### ISSUE TITLE
X-TUNNEL 近300G流量没了

### ISSUE THREAD

**Issue by XX-NETGOOD** [XX-net/XX-Net#10871]
账号: liuhonging520@gmail.com 请查证

**Comment by SeaHOH** [comment]
#10868

**Comment by dohoney** [comment]
同样的问题，请查证
账号：du-xy15@mails.tsinghau.edu.cn

**Comment by JemmyLuck** [comment]
同样问题，1100多Gi流量不见了

**Comment by SeaHOH** [comment]
等几天把攻击对付过去了，应该会再出个公告，到时会处理。

**Comment by zeitgeist8080** [comment]
1000多G 没了，用不了， 308038858@qq.com

**Comment by lluoyulin** [comment]
和我的问题一样，突然370G流量不在了

**Comment by lluoyulin** [comment]
已经可以了，恢复正常



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：freedom_luo@sina.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master
            在2018年06月06日 20:25，Michael.X 写道： ​流量丢失已经修复，请大家重新刷新看看



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/XX-net/XX-Net/issues/10871#issuecomment-395049888","url":"https://github.com/XX-net/XX-Net/issues/10871#issuecomment-395049888","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/XX-net/XX-Net","title":"XX-net/XX-Net","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/XX-net/XX-Net"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xxnet in #10871: ​流量丢失已经修复，请大家重新刷新看看\r\n"}],"action":{"name":"View Issue","url":"https://github.com/XX-net/XX-Net/issues/10871#issuecomment-395049888"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [XX-net/XX-Net] X-TUNNEL 近300G流量没了 (#10871)",
"sections": [
{
"text": "",
"activityTitle": "**Michael.X**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@xxnet",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"XX-net/XX-Net\",\n\"issueId\": 10871,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"XX-net/XX-Net\",\n\"issueId\": 10871\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/XX-net/XX-Net/issues/10871#issuecomment-395049888"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 342034429\n}"
}
],
"themeColor": "26292E"
}
