### ISSUE TITLE
Mac Mojave 系统无法使用

### ISSUE THREAD

**Issue by ZiYang233** [XX-net/XX-Net#11505]
无法开启 iPv6, 10.13 下可以使用.

**Comment by marvina** [comment]
按步骤重新安装一遍
 teredo 就行了

**Comment by CoffeeWu** [comment]
macports要用命令行安装，.pkg会提示系统版本不对。
https://www.macports.org/install.php
拉到下面Source Installation，根据提示安装就行，
其他步骤参考#8425

**Comment by ZiYang233** [comment]
重新安装 teredo 已解决

**Comment by shenguanjiejie** [comment]
重新安装teredo,安装器提示:软件包版本与系统不兼容
按照Source Installation安装已成功(Congratulations, you have successfully installed the MacPorts system.),但是执行port命令提示:
$ port selfupdate
zsh: command not found: port

不知道为什么我这里是不行的,求帮助 : )

**Comment by shenguanjiejie** [comment]
不知道Source installation这些步骤是不是必须的,有点看不明白,我还没有配置这些:
To customize your installation you should read the output of “./configure --help | more” and pass the appropriate options for the settings you wish to tweak to the configuration script in the steps detailed above.

You will need to manually adapt your shell's environment to work with MacPorts and your chosen installation prefix (the value passed to configure's --prefix flag, defaulting to /opt/local):

Add ${prefix}/bin and ${prefix}/sbin to the start of your PATH environment variable so that MacPorts-installed programs take precedence over system-provided programs of the same name.
If a standard MANPATH environment variable already exists (that is, one that doesn't contain any empty components), add the ${prefix}/share/man path to it so that MacPorts-installed man pages are found by your shell.
For Tiger and earlier only, add an appropriate X11 DISPLAY environment variable to run X11-dependent programs, as Leopard takes care of this requirement on its own.
Lastly, you need to synchronize your installation with the MacPorts rsync server:

sudo port -v selfupdate
Upon completion MacPorts will be ready to install ports!

It is recommended to run the above command on a regular basis to keep your installation current. Type “man port” at the command line prompt and/or browse over to our Guide to find out more information about using MacPorts. Help is also available.

如果是必须的 希望能解答一下,这是什么意思,要怎么配置.

**Comment by CoffeeWu** [comment]
要编辑一下这个文件"/etc/paths"，让终端找到程序放在哪
加上这2行
/opt/local/bin
/opt/local/sbin
再重启终端即可

**Comment by iikk** [comment]
`--->  Computing dependencies for miredo
The following dependencies will be installed: 
 gettext
 gperf
 libiconv
 ncurses
 tuntaposx
 xz
Continue? [Y/n]: y
--->  Building tuntaposx
Error: Failed to build tuntaposx: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_tuntaposx/tuntaposx/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port miredo failed`

装好macports后 执行sudo port install miredo报错。你们怎么解决的？

**Comment by shenguanjiejie** [comment]
@iikk  是不是系统保护没有关

**Comment by zhilidali** [comment]
> `---> Computing dependencies for miredo The following dependencies will be installed: gettext gperf libiconv ncurses tuntaposx xz Continue? [Y/n]: y ---> Building tuntaposx Error: Failed to build tuntaposx: command execution failed Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_net_tuntaposx/tuntaposx/main.log for details. Error: Follow https://guide.macports.org/#project.tickets to report a bug. Error: Processing of port miredo failed`
> 
> 装好macports后 执行sudo port install miredo报错。你们怎么解决的？

我的也是这个问题，同求解决
