### ISSUE TITLE
请教x-tunnel有免费流量吗？

### ISSUE THREAD

**Issue by OP83** [XX-net/XX-Net#13656]
刚注册的用户，用最新版xxnet测试了一下上谷歌首页很快，走了20几k的流量。我看页面显示套餐流量是0，那我用了几十k要收费吗？

**Comment by XuanmiaoG** [comment]
xx- tunnel 免费流量500mb

**Comment by OP83** [comment]
> xx- tunnel 免费流量500mb

这个免费流量是每天的量还是永久就这么多免费的量呢？另外，如果用完了免费的量是不是就会自动上不去了，不会额外产生账单什么的吧？谢谢！

**Comment by XuanmiaoG** [comment]
总共的免费的，用完就用不了tunnel了，只能用GAE了也不会有欠费这种东西---- 回复的原邮件 ***@***.***>发送日期2022年02月28日 09:35 ***@***.***> ***@***.******@***.***>主题Re: [XX-net/XX-Net] 请教x-tunnel有免费流量吗？ (Issue #13656)



xx- tunnel 免费流量500mb



这个免费流量是每天的量还是永久就这么多免费的量呢？另外，如果用完了免费的量是不是就会自动上不去了，不会额外产生账单什么的吧？谢谢！



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you commented.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/XX-net/XX-Net/issues/13656#issuecomment-1053774169",

"url": "https://github.com/XX-net/XX-Net/issues/13656#issuecomment-1053774169",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by OP83** [comment]
> 总共的免费的，用完就用不了tunnel了，只能用GAE了也不会有欠费这种东西---- 回复的原邮件 ***@***.***>发送日期2022年02月28日 09:35 ***@***.***> ***@***.******@***.***>主题Re: [XX-net/XX-Net] 请教x-tunnel有免费流量吗？ (Issue #13656) xx- tunnel 免费流量500mb 这个免费流量是每天的量还是永久就这么多免费的量呢？另外，如果用完了免费的量是不是就会自动上不去了，不会额外产生账单什么的吧？谢谢！ —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#13656 (comment)](https://github.com/XX-net/XX-Net/issues/13656#issuecomment-1053774169)", "url": "[#13656 (comment)](https://github.com/XX-net/XX-Net/issues/13656#issuecomment-1053774169)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

多谢了！GAE我没绑卡也用不了，看来是用不了xxnet了，只能找别的方法了。
