### ISSUE TITLE
Ubuntu 如何开机启动，并且平时启动的时候关了命令窗口就无法使用

### ISSUE THREAD

**Issue by liyangio** [XX-net/XX-Net#1698]
搜了一段时间，没有发现相关的教程，麻烦作者发个教程。在网页控制端设置开机启动貌似也无效

**Comment by xxnet** [comment]
手动的参考这个教程：
http://askubuntu.com/questions/459277/how-do-i-make-a-program-auto-start-everytime-i-log-in-in-ubuntu-14-04

自动的还要改代码

在 2015年12月24日 上午10:16，Li Yang <notifications@github.com>写道：

**Comment by xxnet** [comment]
代码已改好，未发版本，你可以通过这个链接测试：
https://github.com/XX-net/XX-Net/archive/master.zip

**Comment by largewhale** [comment]
ubuntu12.04， xxnet273。我在终端中必须用sudo start来启动，如果直接用start，会提示权限的错误。但是，在教程里，仅提到第一次启动需要用到sudo （是说以后都可以不用sudo的意思么？），难道是我漏了什么地方？

此外，作者在楼上回复的手动添加自启教程中，如果在startup设置中，似乎无法直接用sudo 命令。

**Comment by largewhale** [comment]
ubuntu14.04， xxnet273. xxnet随系统自启的方法。
用root权限，打开/etc/rc.local，：

-------------------------
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.
/xxx/xxx/start.sh             （加入这一句）
exit 0
--------------

其中xxx为xx-net的绝对路径。

实测成功！

**Comment by xxnet** [comment]
​>如果直接用start，会提示权限的错误。
具体什么异常？贴出来看看

**Comment by largewhale** [comment]
就这个情况：
whale@whale-Lenovo-Product:~$ /home/whale/fuckgfw/XX-Net-2.7.3/start.sh
Traceback (most recent call last):
  File "launcher/start.py", line 13, in <module>
    import launcher_log
  File "/home/whale/fuckgfw/XX-Net-2.7.3/launcher/launcher_log.py", line 57, in <module>
    log_fd = open(log_path, "a")
IOError: [Errno 13] Permission denied: '/home/whale/fuckgfw/XX-Net-2.7.3/data/launcher/log.log'
whale@whale-Lenovo-Product:~$ 

如果加了sudo，就万事大吉 ：）

**Comment by xxnet** [comment]
​你的目录已经是sudo执行过，所以文件权限变成root的了，要改过来

sudo chown whale -R /home/whale/fuckgfw/XX-Net-2.7.3

**Comment by largewhale** [comment]
这样啊！！

只是因为第一次sudo执行造成的么？我自己肯定没有做过目录的权限修改。

如果是因为第一次sudo执行造成的，那教程里要加上哦。我折腾了一晚上，才搞定root权限启动。小白一枚，不要意思。

**Comment by largewhale** [comment]
按照x大指导，问题解决。多谢！
