### ISSUE TITLE
请检查浏览器代理设置，证书fail

### ISSUE THREAD

**Issue by Asureu** [XX-net/XX-Net#5042]
XX-Net Status:

sys-platform: x86, Windows-10-10.0.14393
os-system: Windows
os-version: 10.0.14393
os-release: 10
os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0
architecture: 32bit,WindowsPE
browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
xxnet-version: 3.2.9

python-version: 2.7.11
openssl-version: 16.0.0 TLSv1_2 h2:alpn

ipv6-status: 0
gws-ip-num: total:1084 good:414
network-status: OK
connected-link: new:4 used:0
worker: h1:27 h2:11
scan-ip-thread-num: 50
ip-quality: 740
is-idle: 0
block-stat: OK
proxy_state: Fail
ca_state: Fail
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false
图片：
[
![image](https://cloud.githubusercontent.com/assets/25910710/23151345/f44c50a4-f834-11e6-8e29-c4d098730ff8.png)
](url)
[
![image](https://cloud.githubusercontent.com/assets/25910710/23151360/116e3ddc-f835-11e6-962a-5ffea6a4c0ff.png)
](url)

描述：能够科学上网，包括国内外的http和https，但是状态信息显示“请检查浏览器代理设置”，证书设置fail，不知道是否正常。常用的pac智能代理。
另外，自己装了Tampermonkey 插件，里面有个去百度推广的脚本，会有影响吗？

**Comment by kirbyzhu** [comment]
试试Ctrl f5强制刷新当前页面 发自网易邮箱手机版 在2017年02月21日 13:00 ，Asureu写道： XX-Net Status: sys-platform: x86, Windows-10-10.0.14393 os-system: Windows os-version: 10.0.14393 os-release: 10 os-detail: Version:10-0; Build:14393; Platform:2; CSD:; ServicePack:0-0; Suite:768; ProductType:0 architecture: 32bit,WindowsPE browser: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 xxnet-version: 3.2.9 python-version: 2.7.11 openssl-version: 16.0.0 TLSv1_2 h2:alpn ipv6-status: 0 gws-ip-num: total:1084 good:414 network-status: OK connected-link: new:4 used:0 worker: h1:27 h2:11 scan-ip-thread-num: 50 ip-quality: 740 is-idle: 0 block-stat: OK proxy_state: Fail ca_state: Fail Appid_Working: true Appids_Out_Of_Quota: false Appids_Not_Exist: false Using_Public_Appid: false 图片： 描述：能够科学上网，包括国内外的http和https，但是状态信息显示“请检查浏览器代理设置”，证书设置fail，不知道是否正常。常用的pac智能代理。 另外，自己装了Tampermonkey 插件，里面有个去百度推广的脚本，会有影响吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Asureu** [comment]
可以了！十分感谢大神！
然后，还有几个小问题请教一下：
1.怎么设置手机通过XX-Net上网，或者给个相关链接我自己学也行
2.免费appid的限额满了的话是不是就断了链接了
3.自己已经有个appid弄了KindleEar订阅rss，这个appid也可以用来部署吗
4.打开Tampermonkey的时候速度明显减慢了，然后停用又正常了，用哪个插件屏蔽广告可以不影响xx-net？

**Comment by kirbyzhu** [comment]
1 https://github.com/XX-net/XX-Net/wiki/%E4%B8%BA%E5%85%B6%E4%BB%96%E8%AE%BE%E5%A4%87%E6%8F%90%E4%BE%9B%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1

更详细的步骤

转：分享XX-Net的局域网共享代理方法 （安卓手机/局域网内其他电脑）
https://groups.google.com/forum/#!topic/xx-net/mZljXXRwL-4
一.电脑端操作
1.在XXnet/data/gae_proxy目录下修改config.ini 将127.0.0.1改为0.0.0.0（这样设置本地+局域网都有效）
[pac]
enable = 1
ip = 0.0.0.0
port = 8086
file = proxy.pac
gfwlist = https://raw.githubusercontent.com/gfwlist/gfwlist/master/gfwlist.txt
;adblock = http://adblock-chinalist.googlecode.com/svn/trunk/adblock.txt
; this project have stopped.
expired = 86400
[listen]
ip = 0.0.0.0
port = 8087
visible = 1
debuginfo = 0

2.重启XX-Net，确认本地仍可正常翻墙。


二.局域网内其他电脑
1.Win+R输入cmd回车，输入ipconfig，获取到本机IPv4地址192.x.x.x

2.局域网内其他主机，IE--Internet设置--连接--代理服务器，设为刚查到的192.x.x.x 端口8087。Chrome等浏览器在插件如switchy sharp里同样设置即可。


三.局域网手机端

方法一：将XX-Net-2.5.5\data\gae_proxy下的CA.crt复制到手机sd卡。打开设置-安全-存储凭证-从sd卡安装，安装ca.crt 。重启手机

方法二：若方法一无发安装，打开网址 Main - RealmB's Android Certificate Installer 将XX-Net\data\gae_proxy\CA.crt证书上传，得到一个链接，手机访问可以直接安装证书（安装选择类型WLAN），感谢RealmB！

注意：：安装类型选择wlan，不能正常使用。

3.打开设置-wifi-你连接的wifi，把代理改成手动，主机名填你的静态ip，端口填8087

4.这时你的手机应该也能够通过XX-Net翻墙了！

注意：电脑关机后需将手机的代理调回无，才能正常上网（无翻墙）

2 免费的appid很多 一般不会满

3 可以部署

4 我用adblock没问题
