### ISSUE TITLE
请等待大约半小时，XX-Net需要扫描IP。

### ISSUE THREAD

**Issue by yxgi5** [XX-net/XX-Net#6502]
XX-Net Status:

sys-platform: x86_64, Linux-4.9.0-0.bpo.3-amd64-x86_64-with-debian-8.9
os-system: Linux
os-version: #1 SMP Debian 4.9.30-2+deb9u2~bpo8+1 (2017-06-27)
os-release: 4.9.0-0.bpo.3-amd64
os-detail: Dist:debian; Version:8.9; ID:
architecture: 64bit,ELF
browser: Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
xxnet-version: 3.4.2

python-version: 2.7.9
openssl-version: 16.0.0 TLSv1_2 h2:npn

ipv6-status: 0
gws-ip-num: total:3000 good:0
network-status: OK
connected-link: new:0 used:0
worker: h1:0 h2:0
scan-ip-thread-num: 50
ip-quality: 9999
is-idle: 0
block-stat: OK
proxy_state: OK
ca_state: OK
Appid_Working: true
Appids_Out_Of_Quota: false
Appids_Not_Exist: false
Using_Public_Appid: false

**Comment by eacdy** [comment]
same problem.

**Comment by qiurongli** [comment]
我也是这样的。好几天了。不知道怎么办了。

**Comment by mtt3366** [comment]
同样的问题

**Comment by beyondyun** [comment]
me too

**Comment by 2579019321** [comment]
同样的问题

**Comment by offeca** [comment]
同样的问题，ip值都是0

**Comment by if2012** [comment]
同样的问题，原来你已经提过了。

**Comment by Neofly1992** [comment]
同样的问题

**Comment by yxgi5** [comment]
update to XX-Net 3.5.6

**Comment by beyondyun** [comment]
Is that work ？
发自网易邮箱大师
在2017年09月22日 08:39，yxgi5 写道： update to XX-Net 3.5.6

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/XX-net/XX-Net","title":"XX-net/XX-Net","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/XX-net/XX-Net"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yxgi5 in #6502: update to XX-Net 3.5.6"}],"action":{"name":"View Issue","url":"https://github.com/XX-net/XX-Net/issues/6502#issuecomment-331318865"}}}
