### ISSUE TITLE
xx-net name suggestion

### ISSUE THREAD

**Issue by kuchaguangjie** [XX-net/XX-Net#887]
Hi, I just setup xxnet, it's great I think, just that the name is a little wield.

I suggest to use "xnet" as the name, and the root folder, so that on linux when need to enter the folder I don't need to press `Caps Lock` key any more, also press '-' is also difficult for me :)

Anyhow it's just a suggestion.

**Comment by uawha** [comment]
Hi, the word "wield" is not an adjective in any case. I think you mean "weird".
But you can speak Chinese here, if you know the language.

I don't think the project master should change the name just to suit your trivial need.

But to solve your problem:
Assuming you are using bash:
If you has a folder named `XX-Net`, and its full path is `/a/XX-Net`:
1. If you need to type the folder name and your current folder is `/a`, go to the `Solution`;
2. If you need to type the path, first type `/a/`, then go to the `Solution`. This works whatever your current folder is.

`Solution`:
Press `Shift` +  `x`, then again, then press `Tab` until `XX-Net` shows up.

**Comment by kuchaguangjie** [comment]
@uawha About the path, I did rename the git repository to `xxnet` after download, and defined a serial of shortcut in `.bashrc` to cd / edit / kill / restart with single command, for me this is not an issue I guess.

My key point is that, a neat & simple name would make the project better, If you have watch the movie <Social network>, you know facebook is come from 'thefacebook', they drop the `the` to make it neat.

I do speak Chinese, I am from China mainland, but I think `xx-net` or `goagent` is also useful to people who don't speak Chinese. They might want to participate too.

Anyhow, as I have make it very clear that this is just my personal opinion & suggestion, I think a good product & community, would allow all kinds of suggestion even bad ones, that's called `Freedom of speech`, which is very lack in our own country.

**Comment by lele2010lele** [comment]
佩服佩服，我虽然能看懂英文，但我不会用英文回复。。。。两位也算让人崇拜了

**Comment by uawha** [comment]
@kuchaguangjie 

I wonder what prevented you from saying your real motivation.
Apparently you are not some ungrateful selfish user who's demanding someone else to take care of his own problem which is a problem only because he is lazy.
So do not act like one. Your origin motivation is not trivial. Don't hide it, cause in this case it matters. And if you do want to hide, just think how many of your readers would care enough to guess what is it that you are really up to.

A good name does help `facebook`. But would it help in XX-Net's case?
I don't want to answer this question.
One can argue that XX-Net is non-commercial thus there is no point to make such change of which old user might be annoyed, because when they deploy new systems, there is a chance that they need to change the scripts they wrote before.
But I don't want to talk about the argument, nor do I want to defend it.
It could be wrong in many ways, or simply doesn't matter. I don't care.

What I do care is `Freedom of Speech`.
You are abusing `Freedom of Speech` from the very beginning.
Let me explain.
We say we don't have `Freedom of Speech` in China. This is true because, when you have many audience, the government threaten you with many things (including your life) to make you not saying what they do not want to hear.
We say *Je suis Charlie* harmed `Freedom of Speech`. This is true because this is a similar case, just this time it is the terrorists who do the threat.

But here we have GitHub Issue & Issue Comment system. It is like a forum.
How do you define `Freedom of Speech` in a forum?
It is not the same thing as in China, nor as *Je suis Charlie*.
And it is certainly not "the forum should allow all kinds of speeches". It does not work this way.
Say you run a forum.
One day someone posted a bunch of crap.
So you banned his ID.
The second day another ID posted the same bunch of crap under the name of `Freedom of Speech`.
What would you do?

`Freedom of Speech` comes at a price.
We hope the forum users would regulate themselves.
In this case,
When you demand something, you should at least explain explicitly why you want it.
Your reasons had better be legit. Not some trivial personal needs of which your first post is about.

When one demands something in this way, it is better that someone else points out that one's trivial personal needs do not justify his demand.

That is the price to pay for `Freedom of Speech` in a forum.

**Comment by kuchaguangjie** [comment]
@uawha I didn't intend to hide the purpose, I just express it in a funny way, like a sence of humor, or a joke.Don't be so serious, man.
